# Environment-scoped least-privilege IAM role. The trust + permission policy
# is generated by `cloudenv iam` (see cloudenv/iam_policy.py) and passed in
# as JSON so the Terraform-side and Python-side definitions never drift —
# Terraform just renders what the CLI already validated and unit-tests.

data "aws_iam_policy_document" "assume_role" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/Environment"
      values   = [var.environment]
    }
  }
}

resource "aws_iam_role" "env_role" {
  name               = "${local.name_prefix}-role"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
  tags               = local.common_tags

  # Roles created by ephemeral Dev/QA environments should never outlive
  # the resources they govern.
  max_session_duration = 3600
}

resource "aws_iam_policy" "env_policy" {
  name        = "${local.name_prefix}-policy"
  description = "Least-privilege policy scoped to ${var.environment}/${var.owner} resources only."
  policy      = file("${path.module}/../../generated/${var.environment}-${var.owner}-aws-policy.json")

  tags = local.common_tags
}

resource "aws_iam_role_policy_attachment" "env_attach" {
  role       = aws_iam_role.env_role.name
  policy_arn = aws_iam_policy.env_policy.arn
}
