variable "environment" {
  description = "Environment name: dev or qa."
  type        = string
  validation {
    condition     = contains(["dev", "qa"], var.environment)
    error_message = "environment must be \"dev\" or \"qa\"."
  }
}

variable "owner" {
  description = "Requesting developer/PR author — used for tagging and IAM scoping."
  type        = string
}

variable "project" {
  description = "Project label applied to every resource."
  type        = string
  default     = "cloudenv-provisioner"
}

variable "region" {
  description = "AWS region to provision the environment in."
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = "EC2 instance type for the Dev/QA workload."
  type        = string
  default     = "t3.micro"
}

variable "cost_threshold_usd" {
  description = "Monthly cost threshold that triggers a CloudWatch billing alarm + SNS notification."
  type        = number
  default     = 25
}

variable "alert_email" {
  description = "Email address subscribed to the cost-alert SNS topic."
  type        = string
  default     = ""
}

variable "tags" {
  description = "Canonical tag set generated by `cloudenv tag` (Environment, Owner, Project, ManagedBy, ExpiryDate, Cloud)."
  type        = map(string)
}
