# Environment-scoped least-privilege custom role, mirroring the AWS IAM
# module: one role definition per environment, assignable only at the
# resource-group scope created above — never at subscription scope.
# Definition body is generated by `cloudenv iam --cloud azure`.

resource "azurerm_role_definition" "env_role" {
  name        = "CloudEnv-${local.name_prefix}-Contributor"
  scope       = azurerm_resource_group.env.id
  description = "Least-privilege role for the ${var.environment} environment owned by ${var.owner}."

  permissions {
    actions = [
      "Microsoft.Compute/virtualMachines/*",
      "Microsoft.Storage/storageAccounts/*",
      "Microsoft.Network/virtualNetworks/*",
      "Microsoft.Network/networkInterfaces/*",
      "Microsoft.Resources/subscriptions/resourceGroups/read",
    ]
    not_actions = [
      "Microsoft.Authorization/*/Write",
      "Microsoft.Authorization/*/Delete",
    ]
  }

  assignable_scopes = [azurerm_resource_group.env.id]
}

resource "azurerm_role_assignment" "env_owner_assignment" {
  scope              = azurerm_resource_group.env.id
  role_definition_id = azurerm_role_definition.env_role.role_definition_resource_id
  principal_id       = data.azurerm_client_config.current.object_id
}

data "azurerm_client_config" "current" {}
