variable "environment" {
  description = "Environment name: dev or qa."
  type        = string
  validation {
    condition     = contains(["dev", "qa"], var.environment)
    error_message = "environment must be \"dev\" or \"qa\"."
  }
}

variable "owner" {
  description = "Requesting developer/PR author — used for tagging and role scoping."
  type        = string
}

variable "project" {
  type    = string
  default = "cloudenv-provisioner"
}

variable "location" {
  description = "Azure region to provision the environment in."
  type        = string
  default     = "eastus"
}

variable "vm_size" {
  type    = string
  default = "Standard_B1s"
}

variable "cost_threshold_usd" {
  description = "Monthly budget amount that triggers an Azure Monitor action group alert."
  type        = number
  default     = 25
}

variable "alert_email" {
  type    = string
  default = ""
}

variable "admin_username" {
  type    = string
  default = "cloudenvadmin"
}

variable "ssh_public_key" {
  description = "SSH public key for the Dev/QA VM — never store a private key or password in Terraform state."
  type        = string
}

variable "tags" {
  description = "Canonical tag set generated by `cloudenv tag`."
  type        = map(string)
}
